### ISSUE TITLE
When generating beans using the dart mappable mixin method, the output content of json. encode (bean) includes "\"

### ISSUE THREAD

**Issue by Clearlove2015** [eitanliu/dart_mappable_plugin#1]
{
"code": 0,
"desc": "success",
"data": {
"uuid": "7acf6364-ea13-49ee-9c8a-63a231de2608",
"username": "jklove",
}
}

var str = login.toJson(); 
var bean = LoginMappableMixinBean.fromJson(str);
logTAG("===>out: ${json.encode(bean)}");

out content:
"{\\"code\\":0,\\"desc\\":\\"dd\\",\\"data\\":{\\"uuid\\":\\"7acf6364-ea13-49ee-9c8a-63a231de2608\\",\\"username\\":\\"jklove\\"}}"

**Comment by eitanliu** [comment]
Can you provide a sample project?
I need to know which dependencies are used.

**Comment by Clearlove2015** [comment]
> Can you provide a sample project? I need to know which dependencies are used.

[mappable_mixin.zip](https://github.com/user-attachments/files/17613482/mappable_mixin.zip)

The project is too large to upload, I have compiled the main code of the problem

**Comment by eitanliu** [comment]
The generated beans determined by  [dart_mappable](https://github.com/schultek/dart_mappable), for related  issues see [https://github.com/schultek/dart_mappable/issues/82](https://github.com/schultek/dart_mappable/issues/82).

Other alternatives is  use `toMap() ` 
```dart
logTAG("===>login2 Json: ${json.encode(login2.toMap())}");
```

**Comment by Clearlove2015** [comment]
> The generated beans determined by [dart_mappable](https://github.com/schultek/dart_mappable), for related issues see [schultek/dart_mappable#82](https://github.com/schultek/dart_mappable/issues/82).
> 
> Other alternatives is use `toMap() `
> 
> ```dart
> logTAG("===>login2 Json: ${json.encode(login2.toMap())}");
> ```

I have read this issue before and think that toMap is not very good, such as the List\<Item\> scene
